"""Shared DB access: SQLite locally, pooled PostgreSQL when DATABASE_URL is set."""
import os
import re
import sqlite3
import threading

_pool = None
_pool_lock = threading.Lock()
_schema_lock = threading.Lock()
_schema_ready = False


def database_url():
    return os.environ.get("DATABASE_URL", "").strip()


def uses_postgres():
    return database_url().startswith(("postgres://", "postgresql://"))


def _get_pool():
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                from psycopg_pool import ConnectionPool
                _pool = ConnectionPool(
                    database_url(), min_size=1,
                    max_size=int(os.environ.get("AIWA_PG_POOL_MAX", "10")),
                )
    return _pool


def _pg_sql(sql):
    # Application SQL never uses question marks as string literals.
    return re.sub(r"\?", "%s", sql)


class PostgresConnection:
    """Small sqlite3-compatible facade used by the existing repositories."""
    def __init__(self):
        self._lease = _get_pool().connection()
        self._conn = self._lease.__enter__()

    def execute(self, sql, params=None):
        return self._conn.execute(_pg_sql(sql), params or ())

    def executemany(self, sql, params):
        return self._conn.executemany(_pg_sql(sql), params)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        if self._conn is not None:
            self._lease.__exit__(None, None, None)
            self._conn = None


def connect(sqlite_path):
    if uses_postgres():
        conn = PostgresConnection()
        ensure_postgres_schema(conn)
        return conn
    conn = sqlite3.connect(sqlite_path, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


POSTGRES_SCHEMA = (
    """CREATE TABLE IF NOT EXISTS users(chat_id BIGINT PRIMARY KEY, last_period TEXT, cycle_len INTEGER,
       send_time TEXT DEFAULT '08:00', modules TEXT DEFAULT 'phase,general,food,training', state TEXT,
       pending_date TEXT, created TEXT, height INTEGER, weight DOUBLE PRECISION, age INTEGER, activity INTEGER,
       diet TEXT, partner_code TEXT, mode TEXT, diet_note TEXT, period_end TEXT, period_len INTEGER,
       train_profile TEXT, kcal_goal INTEGER, last_phase_notified TEXT, last_reactivation TEXT,
       proactive_enabled INTEGER DEFAULT 1)""",
    "CREATE TABLE IF NOT EXISTS sugg(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT, q TEXT)",
    "CREATE TABLE IF NOT EXISTS cycles(chat_id BIGINT, start_date TEXT, end_date TEXT, PRIMARY KEY(chat_id,start_date))",
    "CREATE TABLE IF NOT EXISTS intimacy(chat_id BIGINT, d TEXT, PRIMARY KEY(chat_id,d))",
    "CREATE TABLE IF NOT EXISTS chat_log(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT, ts TEXT, role TEXT, text TEXT)",
    "CREATE TABLE IF NOT EXISTS logs(chat_id BIGINT, log_date TEXT, energy INTEGER, mood INTEGER, symptoms TEXT, PRIMARY KEY(chat_id,log_date))",
    """CREATE TABLE IF NOT EXISTS events(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT,
       ts TEXT, action TEXT, tokens INTEGER DEFAULT 0, meta TEXT, ms INTEGER DEFAULT 0, n INTEGER DEFAULT 0,
       calls INTEGER DEFAULT 0, tok_in INTEGER DEFAULT 0, tok_out INTEGER DEFAULT 0, model TEXT)""",
    "CREATE TABLE IF NOT EXISTS partners(partner_id BIGINT PRIMARY KEY, woman_id BIGINT, created TEXT)",
    """CREATE TABLE IF NOT EXISTS meals(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT,
       d TEXT, ts TEXT, title TEXT, kcal INTEGER DEFAULT 0, protein DOUBLE PRECISION DEFAULT 0,
       fat DOUBLE PRECISION DEFAULT 0, carbs DOUBLE PRECISION DEFAULT 0, grams INTEGER, items TEXT,
       source TEXT, slot TEXT, fclass TEXT)""",
    """CREATE TABLE IF NOT EXISTS workouts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT,
       d TEXT, ts TEXT, type TEXT, items TEXT, duration TEXT, rpe TEXT, note TEXT, review TEXT,
       kcal INTEGER DEFAULT 0, muscles TEXT)""",
    """CREATE TABLE IF NOT EXISTS proactive_log(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       chat_id BIGINT, ts TEXT, signal TEXT, score INTEGER DEFAULT 0, sent INTEGER DEFAULT 0, text TEXT)""",
    "CREATE TABLE IF NOT EXISTS proactive_state(chat_id BIGINT, signal TEXT, last_ts TEXT, PRIMARY KEY(chat_id,signal))",
    "CREATE TABLE IF NOT EXISTS memory(chat_id BIGINT, mkey TEXT, mval TEXT, updated TEXT, PRIMARY KEY(chat_id,mkey))",
    "CREATE TABLE IF NOT EXISTS referrals(chat_id BIGINT PRIMARY KEY, source TEXT, ts TEXT)",
    """CREATE TABLE IF NOT EXISTS push_deliveries(chat_id BIGINT NOT NULL, campaign_id TEXT NOT NULL,
       status TEXT NOT NULL, claimed_at TEXT NOT NULL, sent_at TEXT, PRIMARY KEY(chat_id,campaign_id))""",
    """CREATE TABLE IF NOT EXISTS events_v2(event_id TEXT PRIMARY KEY, occurred_at TEXT NOT NULL, user_key TEXT,
       event_name TEXT NOT NULL, source TEXT NOT NULL, screen TEXT, request_id TEXT, session_id TEXT, status TEXT,
       latency_ms INTEGER DEFAULT 0, properties_json TEXT NOT NULL DEFAULT '{}', app_version TEXT,
       dedupe_key TEXT UNIQUE)""",
    """CREATE TABLE IF NOT EXISTS llm_calls(call_id TEXT PRIMARY KEY, occurred_at TEXT NOT NULL, user_key TEXT,
       request_id TEXT, provider TEXT NOT NULL, model TEXT, purpose TEXT, status TEXT NOT NULL,
       latency_ms INTEGER DEFAULT 0, input_tokens INTEGER DEFAULT 0, output_tokens INTEGER DEFAULT 0,
       cached_tokens INTEGER DEFAULT 0, total_tokens INTEGER DEFAULT 0, retry_index INTEGER DEFAULT 0,
       fallback_from TEXT, reported_cost DOUBLE PRECISION, cost_unit TEXT,
       estimated_cost_usd DOUBLE PRECISION, meta_json TEXT NOT NULL DEFAULT '{}')""",
    """CREATE TABLE IF NOT EXISTS traction_outbox(event_id TEXT PRIMARY KEY, occurred_at DOUBLE PRECISION NOT NULL,
       device_id TEXT NOT NULL, name TEXT NOT NULL, properties_json TEXT NOT NULL DEFAULT '{}',
       payload_version INTEGER NOT NULL DEFAULT 1)""",
    "CREATE TABLE IF NOT EXISTS traction_sent(event_id TEXT PRIMARY KEY, sent_at DOUBLE PRECISION NOT NULL, payload_version INTEGER NOT NULL DEFAULT 1)",
    "CREATE TABLE IF NOT EXISTS user_lifecycle(user_key TEXT PRIMARY KEY, generation INTEGER NOT NULL DEFAULT 1, active INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL)",
    """CREATE TABLE IF NOT EXISTS media_jobs(
       job_id TEXT PRIMARY KEY, chat_id BIGINT NOT NULL, status TEXT NOT NULL,
       filename TEXT NOT NULL, image_data BYTEA, result_json TEXT, error TEXT,
       created_at TEXT NOT NULL, updated_at TEXT NOT NULL)""",
    "CREATE INDEX IF NOT EXISTS ix_events_ts ON events(ts)",
    "CREATE INDEX IF NOT EXISTS ix_events_cid_ts ON events(chat_id,ts)",
    "CREATE INDEX IF NOT EXISTS ix_meals_cid_d ON meals(chat_id,d)",
    "CREATE INDEX IF NOT EXISTS ix_workouts_cid_d ON workouts(chat_id,d)",
    "CREATE INDEX IF NOT EXISTS ix_events_v2_time ON events_v2(occurred_at)",
    "CREATE INDEX IF NOT EXISTS ix_events_v2_user_time ON events_v2(user_key,occurred_at)",
    "CREATE INDEX IF NOT EXISTS ix_events_v2_name_time ON events_v2(event_name,occurred_at)",
    "CREATE INDEX IF NOT EXISTS ix_llm_calls_time ON llm_calls(occurred_at)",
    "CREATE INDEX IF NOT EXISTS ix_llm_calls_request ON llm_calls(request_id)",
    "CREATE INDEX IF NOT EXISTS ix_llm_calls_user_time ON llm_calls(user_key,occurred_at)",
    "CREATE INDEX IF NOT EXISTS ix_traction_outbox_time ON traction_outbox(occurred_at)",
    "CREATE INDEX IF NOT EXISTS ix_media_jobs_chat_created ON media_jobs(chat_id, created_at)",
)


def ensure_postgres_schema(conn):
    global _schema_ready
    if _schema_ready:
        return
    with _schema_lock:
        if _schema_ready:
            return
        for statement in POSTGRES_SCHEMA:
            conn.execute(statement)
        conn.commit()
        _schema_ready = True
