[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile"

[deploy]
startCommand = "python -m aiwa_service api"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
